PSR-1674 [Accessibility] Issue: Confusing error message for pension s…
hmrc/pension-scheme-return-frontend pull request #1007
Opened 2024-12-10 16:10 UTC by cyeniceri

…cheme assets #8760 (AA)

2024-12-10 17:26 UTC, ccatosdevelopment submitted a review, later dismissed

2024-12-11 08:06 UTC, kberec requested changes

2024-12-11 08:06 UTC, kberec commented on app/forms/FormProvider.scala
> +        "value.3" -> fieldMapping(errors3, args.drop(2))
This breaks validation messages in `AmountOfTheLoanController`.
![image](https://github.com/user-attachments/assets/e36ff1fe-52d3-40e5-973c-adeb92392286)


I suggest breaking down args parameter into three separate ones:
```
    args1: Seq[String],
    args2: Seq[String],
    args3: Seq[String]
```


(similar in above method with two errors for consistency,  even though that doesn't seem to break anything)

2024-12-12 13:05 UTC, kberec commented on conf/messages.en
> +valueOfAssets.end.error.required = Enter the total value of the pension scheme’s assets minus liabilities, on {1}, in pounds and pence
Nice :)

2024-12-12 13:05 UTC, kberec approved these changes

2024-12-12 14:22 UTC, merged