PSR-102 startpage content change
hmrc/pension-scheme-return-frontend pull request #22
Opened 2023-02-21 13:45 UTC by narendrapaduchuri

2023-02-21 13:48 UTC, kurtlogan submitted a review, later dismissed

2023-02-21 13:57 UTC, westwater approved these changes

2023-02-23 11:06 UTC, kurtlogan requested changes

2023-02-23 11:06 UTC, kurtlogan commented on app/views/ContentPageView.scala.html
> +                    .asLink(viewmodel.onSubmit.url).asStartButton()
ContentPageView is a generic view for displaying content, not all content pages are start pages so setting the button as a start button will not always apply, you will need to configure that this is a start button in the view model and pass that to the button

2023-02-23 14:19 UTC, kurtlogan approved these changes

2023-02-23 14:50 UTC, westwater approved these changes

2023-02-23 15:27 UTC, merged