PSR-99-2 psa and psp declaration pages
hmrc/pension-scheme-return-frontend pull request #40
Opened 2023-03-10 13:50 UTC by narendrapaduchuri

2023-03-14 16:00 UTC, kurtlogan submitted a review, later dismissed

2023-03-15 12:44 UTC, westwater approved these changes

2023-03-15 12:44 UTC, merged

2023-03-15 13:13 UTC, kurtlogan requested changes

2023-03-15 13:13 UTC, kurtlogan commented on app/navigation/Navigator.scala
> +    case PspDeclarationPage(srn) => _ => routes.UnauthorisedController.onPageLoad
Same for this