PSR-454 PSR-674 Member Removal Issues fixed
hmrc/pension-scheme-return-frontend pull request #664
Opened 2024-04-24 12:00 UTC by B-Savage

2024-04-24 12:14 UTC, kberec commented on app/pages/nonsipp/memberdetails/MemberDetailsPage.scala
> +    removePages(userAnswers, dependantPages(srn))
@B-Savage this removes dependent pages even if the details are getting updated.

2024-04-24 14:23 UTC, kberec commented on app/pages/nonsipp/memberdetails/MemberDetailsPage.scala
> +    removePages(userAnswers, dependantPages(srn))
Some commented code left.

2024-04-24 14:23 UTC, kberec commented on app/pages/nonsipp/memberdetails/MemberDetailsPage.scala
> +      case _ => Try(userAnswers)
This case covers the first three cases too, so the first three are unnecessary.

2024-04-24 15:20 UTC, kberec approved these changes
Discussed sorting issue since this was approved.

2024-04-25 07:41 UTC, kberec requested changes
Let's have a chat about issues with sorting

2024-04-25 08:36 UTC, kberec requested changes

2024-04-25 08:36 UTC, kberec commented on app/controllers/nonsipp/employercontributions/EmployerContributionsMemberListController.scala
> +      val memberList = request.userAnswers.map(MembersDetailsPages(srn)).values.toList
There must be a simplified version too, but IMO this should work:

```
val memberList = request.userAnswers.map(MembersDetailsPages(srn)).toList.sortBy(_._1.toInt).map(_._2)
```

2024-04-26 07:23 UTC, kberec commented on app/controllers/nonsipp/employercontributions/EmployerContributionsMemberListController.scala
> +      val memberList = request.userAnswers.map(MembersDetailsPages(srn)).values.toList
Just to summarise our discussion:
Above is just an example, there must be some nicer solution. 
Also this doesn't fix the scenario where there is a gap in the map of members, the employer contribution is still bound to the wrong member.

2024-04-29 09:49 UTC, cyeniceri commented on app/controllers/nonsipp/employercontributions/EmployerContributionsMemberListController.scala
> +      val maxIndex: Int = memberMap.keys.map(_.toInt).maxOption.getOrElse(-1)
is this "-1" logic working properly when MembersDetailsPages returns empty ? I mean ((0 to -1))

2024-04-29 09:49 UTC, cyeniceri commented on app/controllers/nonsipp/employercontributions/EmployerContributionsMemberListController.scala
> +      val maxIndex: Int = memberMap.keys.map(_.toInt).maxOption.getOrElse(-1)
same here

2024-05-01 06:45 UTC, kberec commented on test/controllers/nonsipp/memberdetails/SchemeMembersListControllerSpec.scala
> +                viewModel(srn, 1, Manual, NormalMode, List((refineMV(1), ("0", memberDetails.fullName), Active)))
Are these "0" values right here? If so, should it be a variable?

2024-05-01 12:57 UTC, kberec approved these changes

2024-05-01 14:07 UTC, merged