PSR-743 Don't POST heldProperty.otherDescription when empty
hmrc/pension-scheme-return-frontend pull request #693
Opened 2024-05-23 11:16 UTC by B-Savage

2024-05-23 13:02 UTC, cyeniceri commented on app/transformations/LandOrPropertyTransactionsTransformer.scala
> +                      otherDescription = if (other.description.nonEmpty) Some(other.description) else None
Could be rewritten as 
`
Option.when(other.description.nonEmpty)(other.description)
`

2024-05-23 14:38 UTC, cyeniceri approved these changes

2024-05-24 06:53 UTC, kberec approved these changes

2024-05-24 06:56 UTC, kberec requested changes
Looks @harishmuddegowda found some issue when testing, after the data is posted and subsequently fetched, please refer to the slack conversation.

2024-05-24 10:24 UTC, cyeniceri commented on app/transformations/LandOrPropertyTransformer.scala
> +                  prop.otherDescription.getOrElse(None)
would it be better if we use :
prop.otherDescription instead prop.otherDescription.getOrElse(None)

2024-05-24 10:29 UTC, cyeniceri commented on app/transformations/LandOrPropertyTransformer.scala
> +                  prop.otherDescription.getOrElse(None)
now it's changed :)

2024-05-24 10:57 UTC, cyeniceri approved these changes

2024-05-24 13:32 UTC, kberec approved these changes

2024-05-24 13:38 UTC, merged