PSR-1608 Provide path for either view and change or standard journey …
hmrc/pension-scheme-return-frontend pull request #987
Opened 2024-12-03 17:31 UTC by hmrc-spifix

…on continue

2024-12-12 07:57 UTC, kberec requested changes

2024-12-12 07:57 UTC, kberec commented on app/controllers/OverviewController.scala
> +              logger.error(s"Could not parse version [$version] to int")
Could you please add something to indicate this error message is for SIPP? This is so if we see a pager duty alert, to know that this relates to SIPP.

2024-12-24 14:29 UTC, westwater approved these changes

2024-12-27 10:53 UTC, tolgatunaaa approved these changes

2024-12-27 10:53 UTC, merged